### ISSUE TITLE
Adding more options to the "other packages" section of YoWASP website?

### ISSUE THREAD

**Issue by mithro** [YoWASP/yowasp.github.io#5]
It would be awesome if you could link to the resources packaged under https://github.com/hdl in your ["Are there other packages"](https://yowasp.org/#are-there-other-packages) section.

 * Conda packages (EDA tooling _and_ cross compilers) -- https://github.com/hdl/conda-eda + https://github.com/hdl/conda-compilers).
 * Docker containers - https://github.com/hdl/containers
 * MINGW packages - https://github.com/hdl/MINGW-packages
 * Android (Termux) - https://github.com/hdl/Termux-packages
 * (maybe) Bazel build rules - https://github.com/hdl/bazel_rules_hdl

**Comment by whitequark** [comment]
> It would be awesome if you could link to the resources packaged under https://github.com/hdl in your ["Are there other packages"](https://yowasp.org/#are-there-other-packages) section.

Is there an overview of all these resources provided by the @hdl organization somewhere? I could link to that, then it wouldn't need to be updated if there are new repositories there or if they're rearranged.

**Comment by whitequark** [comment]
No answer in two years.
